# -*- ii: apisnoop; -*-
#+TITLE: AppsV1 StatefulSet Status lifecycle Test - +3
#+AUTHOR: ii team
#+TODO: TODO(t) NEXT(n) IN-PROGRESS(i) BLOCKED(b) | DONE(d)
#+OPTIONS: toc:nil tags:nil todo:nil
#+EXPORT_SELECT_TAGS: export
#+PROPERTY: header-args:sql-mode :product postgres


* TODO Progress [1/6] :export:
- [X] APISnoop org-flow: [[https://github.com/apisnoop/ticket-writing/blob/master/Appsv1StatefulSetStatusLifecycleTest.org][Appsv1StatefulSetStatusLifecycleTest.org]]
- [ ] Test approval issue: [[https://github.com/kubernetes/kubernetes/issues/#][kubernetes/kubernetes#]]
- [ ] Test PR: kuberenetes/kubernetes#
- [ ] Two weeks soak start date: testgrid-link
- [ ] Two weeks soak end date:
- [ ] Test promotion PR: kubernetes/kubernetes#?

* Identifying an untested feature Using APISnoop                     :export:

According to this APIsnoop query, there are still some remaining StatefulSet endpoints which are untested.

  #+NAME: untested_stable_core_endpoints
  #+begin_src sql-mode :eval never-export :exports both :session none
    SELECT
      endpoint,
      path,
      kind
      FROM testing.untested_stable_endpoint
      where eligible is true
      and endpoint ilike '%StatefulSetStatus'
      order by kind, endpoint desc
      limit 10;
  #+end_src

  #+RESULTS: untested_stable_core_endpoints
  #+begin_SRC example
                   endpoint                 |                              path                               |    kind
  ------------------------------------------+-----------------------------------------------------------------+-------------
   replaceAppsV1NamespacedStatefulSetStatus | /apis/apps/v1/namespaces/{namespace}/statefulsets/{name}/status | StatefulSet
   readAppsV1NamespacedStatefulSetStatus    | /apis/apps/v1/namespaces/{namespace}/statefulsets/{name}/status | StatefulSet
   patchAppsV1NamespacedStatefulSetStatus   | /apis/apps/v1/namespaces/{namespace}/statefulsets/{name}/status | StatefulSet
  (3 rows)

  #+end_SRC


* API Reference and feature documentation                            :export:
- [[https://kubernetes.io/docs/reference/kubernetes-api/][Kubernetes API Reference Docs]]
- [[https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/stateful-set-v1/][Kubernetes API / Workload Resources / StatefulSet]]
- [[https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/apps/v1/statefulset.go][client-go - StatefulSet]]

* The mock test                                                      :export:
** Test outline
1. Create a watch to track stateful set events

2. Create a stateful set with a static label. Confirm that the pods are running.

3. Get the stateful set status. Parse the response and confirm that the stateful set status conditions can be listed.

4. Update the stateful set status. Confirm via the watch that the status has been updated.

5. Patch the stateful set status. Confirm via the watch that the status has been patched.

** Test the functionality in Go

Using an existing [[https://github.com/ii/kubernetes/blob/ca3aa6f5af1b545b116b52c717b866e43c79079b/test/e2e/apps/daemon_set.go#L812-L947][status lifecycle test]] as a template for a new [[https://github.com/ii/kubernetes/blob/statefulset-status-test/test/e2e/apps/statefulset.go#L895-L1021][ginkgo test]] for stateful set lifecycle test.

* Verifying increase in coverage with APISnoop :export:
** Listing endpoints hit by the new e2e test

This query shows the endpoints hit within a short period of running the e2e test

#+begin_src sql-mode :eval never-export :exports both :session none
select distinct  endpoint, right(useragent,63) AS useragent
from testing.audit_event
where endpoint ilike '%StatefulSetStatus%'
and release_date::BIGINT > round(((EXTRACT(EPOCH FROM NOW()))::numeric)*1000,0) - 60000
and useragent like 'e2e%should%'
order by endpoint
limit 10;
#+end_src

#+RESULTS:
#+begin_SRC example
                 endpoint                 |                            useragent
------------------------------------------+-----------------------------------------------------------------
 patchAppsV1NamespacedStatefulSetStatus   | [StatefulSetBasic] should validate Statefulset Status endpoints
 readAppsV1NamespacedStatefulSetStatus    | [StatefulSetBasic] should validate Statefulset Status endpoints
 replaceAppsV1NamespacedStatefulSetStatus | [StatefulSetBasic] should validate Statefulset Status endpoints
(3 rows)

#+end_SRC


* Final notes                                                        :export:

If a test with these calls gets merged, *test coverage will go up by 3 points*

This test is also created with the goal of conformance promotion.

-----  
/sig testing  

/sig architecture  

/area conformance  

* Options :neverexport:
** Delete all events after postgres initialization
   #+begin_src sql-mode :eval never-export :exports both :session none
   delete from audit_event where bucket = 'apisnoop' and job='live';
   #+end_src

* Open Tasks
  Set any open tasks here, using org-todo
** DONE Live Your Best Life
* Footnotes                                                     :neverexport:
  :PROPERTIES:
  :CUSTOM_ID: footnotes
  :END:
