# -*- ii: apisnoop; -*-
#+TITLE: Write CoreV1LimitRange Test - +3
#+AUTHOR: ii team
#+TODO: TODO(t) NEXT(n) IN-PROGRESS(i) BLOCKED(b) | DONE(d)
#+OPTIONS: toc:nil tags:nil todo:nil
#+EXPORT_SELECT_TAGS: export
#+PROPERTY: header-args:sql-mode :product postgres


* TODO Progress [6/6]                                                   :export:
- [X] APISnoop org-flow: [[https://github.com/apisnoop/ticket-writing/blob/master/CoreV1LimitRangeTest.org][CoreV1LimitRangeTest.org]]
- [X] Test approval issue: [[https://issues.k8s.io/112429][112429]]
- [X] Test PR: [[https://pr.k8s.io/112430][#112430]]
- [X] Two weeks soak start date: [[https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&width=5&graph-metrics=test-duration-minutes&include-filter-by-regex=should.list,.patch.and.delete.a.LimitRange.by.collection][testgrid-link]] 4 Oct 2022
- [X] Two weeks soak end date: 18 Oct 2022
- [X] Test promotion PR: [[https://pr.k8s.io/113060][Promote List, Patch and Delete LimitRange test to Conformance - +3 Endpoints #113060]]

* Identifying an untested feature Using APISnoop                     :export:

According to this APIsnoop query, there are still three remaining LimitRange endpoints which are untested.

  #+NAME: untested_stable_core_endpoints
  #+begin_src sql-mode :eval never-export :exports both :session none
    SELECT
      endpoint,
      path,
      kind
      FROM testing.untested_stable_endpoint
      where eligible is true
      and endpoint ilike '%LimitRange%'
      order by kind, endpoint desc
      limit 10;
  #+end_src

  #+RESULTS: untested_stable_core_endpoints
  #+begin_SRC example
                    endpoint                  |                       path                        |    kind
  --------------------------------------------+---------------------------------------------------+------------
   patchCoreV1NamespacedLimitRange            | /api/v1/namespaces/{namespace}/limitranges/{name} | LimitRange
   listCoreV1LimitRangeForAllNamespaces       | /api/v1/limitranges                               | LimitRange
   deleteCoreV1CollectionNamespacedLimitRange | /api/v1/namespaces/{namespace}/limitranges        | LimitRange
  (3 rows)

  #+end_SRC

* API Reference and feature documentation                            :export:

- [[https://kubernetes.io/docs/reference/kubernetes-api/][Kubernetes API Reference Docs]]
- [[https://kubernetes.io/docs/reference/kubernetes-api/policy-resources/limit-range-v1/][Kubernetes API / Policy Resource / LimitRange]]
- [[https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/core/v1/limitrange.go][client-go - LimitRange]]

* Test outline                                                       :export:

#+begin_src
Feature: Test list(All Namespaces), patch and deleteCollection LimitRange api endpoints
#+end_src

- listCoreV1LimitRangeForAllNamespaces

#+begin_src
Scenario: confirm that the list action for all namespaces will apply to a LimitRange
  Given the e2e test has created a LimitRange with a label
  When the test lists all LimitRanges with a label selector
  Then the requested action is accepted without any error
  And one LimitRange is found
#+end_src

- patchCoreV1NamespacedLimitRange

#+begin_src
Scenario: confirm that the patch action will apply the changes to a LimitRange
  Given the e2e test has a LimitRange after the "list" scenario
  And a valid payload has been created
  When the test patches the LimitRange
  Then the requested action is accepted without any error
  And the newly applied changes are found
#+end_src

- deleteCoreV1CollectionNamespacedLimitRange

#+begin_src
Scenario: confirm that the deleteCollection action will remove a LimitRange
  Given the e2e test has a LimitRange after the "patch" scenario
  When the test applies the deleteCollection action with a labelSelector
  Then the requested action is accepted without any error
  And the LimitRange with the label is not found
#+end_src

* E2E Test                                                           :export:

Using a number of existing e2e test practices a new [[https://github.com/ii/kubernetes/blob/create-limitrange-test/test/e2e/scheduling/limit_range.go#L229-L311][ginkgo test]] has been created for three LimitRange endpoints.
The e2e logs for this test are listed below.

#+begin_src
[It] should ensure that a limitRange can be listed, patched and deleted by collection
  /home/heyste/go/src/k8s.io/kubernetes/test/e2e/scheduling/limit_range.go:229
STEP: Creating LimitRange "e2e-limitrange-s69c5" 09/14/22 10:47:30.685
STEP: Listing all LimitRanges with label "e2e-limitrange-s69c5=created" 09/14/22 10:47:30.711
Sep 14 10:47:30.716: INFO: Found limitRange "e2e-limitrange-s69c5" in namespace "limitrange-8238"
STEP: Patching LimitRange "e2e-limitrange-s69c5" 09/14/22 10:47:30.716
Sep 14 10:47:30.733: INFO: LimitRange "e2e-limitrange-s69c5" has been patched
STEP: Delete LimitRange "e2e-limitrange-s69c5" by Collection with labelSelector: "e2e-limitrange-s69c5=patched" 09/14/22 10:47:30.733
STEP: Confirm that the limitRange "e2e-limitrange-s69c5" has been deleted 09/14/22 10:47:30.782
Sep 14 10:47:30.783: INFO: Requesting list of LimitRange to confirm quantity
Sep 14 10:47:30.784: INFO: Found 0 LimitRange with label "e2e-limitrange-s69c5=patched"
Sep 14 10:47:30.784: INFO: LimitRange "e2e-limitrange-s69c5" has been deleted.
#+end_src

* Verifying increase in coverage with APISnoop                       :export:

This query shows which LimitRange endpoints are hit within a short period of running this e2e test

#+begin_src sql-mode :eval never-export :exports both :session none
select distinct  substring(endpoint from '\w+') AS endpoint,
                 right(useragent,80) AS useragent
from testing.audit_event
where endpoint ilike '%LimitRange%'
and release_date::BIGINT > round(((EXTRACT(EPOCH FROM NOW()))::numeric)*1000,0) - 60000
and useragent like 'e2e%should%'
order by endpoint
limit 10;
#+end_src

#+RESULTS:
#+begin_SRC example
                  endpoint                  |                                    useragent
--------------------------------------------+----------------------------------------------------------------------------------
 createCoreV1NamespacedLimitRange           | should ensure that a limitRange can be listed, patched and deleted by collection
 deleteCoreV1CollectionNamespacedLimitRange | should ensure that a limitRange can be listed, patched and deleted by collection
 listCoreV1LimitRangeForAllNamespaces       | should ensure that a limitRange can be listed, patched and deleted by collection
 listCoreV1NamespacedLimitRange             | should ensure that a limitRange can be listed, patched and deleted by collection
 patchCoreV1NamespacedLimitRange            | should ensure that a limitRange can be listed, patched and deleted by collection
(5 rows)

#+end_SRC

* Final notes                                                        :export:

If a test with these calls gets merged, *test coverage will go up by 3 point*

This test is also created with the goal of conformance promotion.

-----
/sig testing

/sig architecture

/area conformance
