# -*- ii: apisnoop; -*-
#+TITLE: Write CoreV1Namespace Finalize Test - +1
#+AUTHOR: ii team
#+TODO: TODO(t) NEXT(n) IN-PROGRESS(i) BLOCKED(b) | DONE(d)
#+OPTIONS: toc:nil tags:nil todo:nil
#+EXPORT_SELECT_TAGS: export
#+PROPERTY: header-args:sql-mode :product postgres


* TODO Progress [6/6]                                                   :export:
- [X] APISnoop org-flow: [[https://github.com/apisnoop/ticket-writing/blob/master/CoreV1NamespaceFinalizeTest.org][CoreV1NamespaceFinalizeTest.org]]
- [X] Test approval issue: [[https://issues.k8s.io/112890][Write e2e test for replaceCoreV1NamespaceFinalize +1 Endpoints #112890]]
- [X] Test PR: [[https://pr.k8s.io/112891][Write e2e test for replaceCoreV1NamespaceFinalize +1 Endpoints #112891]]
- [X] Two weeks soak start date: [[https://testgrid.k8s.io/sig-api-machinery-gce-gke#gce-serial&graph-metrics=test-duration-minutes&include-filter-by-regex=should.apply.a.finalizer.to.a.Namespace&width=5][testgrid-link]] 15 Oct 2022
- [X] Two weeks soak end date: 28 Oct 2022
- [X] Test promotion PR: [[https://pr.k8s.io/113454][Promote replaceCoreV1NamespaceFinalize +1 Endpoints #113454]]

* Identifying an untested feature Using APISnoop                     :export:

According to this APIsnoop query, there are still one remaining Namespace endpoint which is untested.

  #+NAME: untested_stable_core_endpoints
  #+begin_src sql-mode :eval never-export :exports both :session none
    SELECT
      endpoint,
      path,
      kind
      FROM testing.untested_stable_endpoint
      where eligible is true
      and endpoint ilike '%V1Namespace%'
      and endpoint not ilike '%Namespaced%'
      order by kind, endpoint desc
      limit 10;
  #+end_src

  #+RESULTS: untested_stable_core_endpoints
  #+begin_SRC example
              endpoint            |                path                |   kind
  --------------------------------+------------------------------------+-----------
   replaceCoreV1NamespaceFinalize | /api/v1/namespaces/{name}/finalize | Namespace
  (1 row)

  #+end_SRC

* API Reference and feature documentation :export:

- [[https://kubernetes.io/docs/reference/kubernetes-api/][Kubernetes API Reference Docs]]
- [[https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/namespace-v1/][Kubernetes API / Cluster Resources / Namespace]]
- [[https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/core/v1/namespace.go][client-go - Namespace]]
- [[https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/core/v1/namespace_expansion.go#L32-L37][client-go - Namespace (Finalize)]]

* Test outline                                                       :export:

#+begin_src
Feature: Test the Namespace finalize subresource
#+end_src

- replaceCoreV1NamespaceFinalize

#+begin_src
Scenario: confirm that the finalize action will apply to a Namespace
  Given the e2e test has created a test Namespace
  And the Spec.Finalizer is appended with a fake finalizer
  When the test updates the finalize subresource
  Then the requested action is accepted without any error
  And the Spec.Finalizer count will equal two
#+end_src

Note: The test also removes the fake finalize from =Spec.Finalizer= before calling the finalize action on the test namespace a second time.
This will allow the test framework to clean up all namespaces when the e2e finishes, else the test namespace will be stuck in the =Terminating= state.

* E2E Test :export:

Using a number of existing e2e test practices a new [[https://github.com/ii/kubernetes/blob/create-namespace-finalizer-test/test/e2e/apimachinery/namespace.go#L386-L425][ginkgo test]] has been created for one Namespace endpoint.
The e2e logs for this test are listed below.

#+begin_src
[It] should apply a finalizer to a Namespace
  /home/ii/go/src/k8s.io/kubernetes/test/e2e/apimachinery/namespace.go:386
STEP: Creating namespace "e2e-ns-snwdg" 10/06/22 11:45:22.926
Oct  6 11:45:22.937: INFO: Namespace "e2e-ns-snwdg-7128" has []v1.FinalizerName{"kubernetes"}
STEP: Adding e2e finalizer to namespace "e2e-ns-snwdg-7128" 10/06/22 11:45:22.937
Oct  6 11:45:22.945: INFO: Namespace "e2e-ns-snwdg-7128" has []v1.FinalizerName{"kubernetes", "e2e.example.com/fakeFinalizer"}
STEP: Removing e2e finalizer from namespace "e2e-ns-snwdg-7128" 10/06/22 11:45:22.945
Oct  6 11:45:22.951: INFO: Namespace "e2e-ns-snwdg-7128" has []v1.FinalizerName{"kubernetes"}
#+end_src

* Verifying increase in coverage with APISnoop                       :export:

This query shows that the Finalize endpoint is hit within a short period of running this e2e test

#+begin_src sql-mode :eval never-export :exports both :session none
select distinct substring(endpoint from '\w+') AS endpoint,
                right(useragent,39) AS useragent
from testing.audit_event
where endpoint ilike '%Finalize%'
and release_date::BIGINT > round(((EXTRACT(EPOCH FROM NOW()))::numeric)*1000,0) - 60000
and useragent like 'e2e%should%'
order by endpoint
limit 10;
#+end_src

#+RESULTS:
#+begin_SRC example
            endpoint            |                useragent
--------------------------------+-----------------------------------------
 replaceCoreV1NamespaceFinalize | should apply a finalizer to a Namespace
(1 row)

#+end_SRC

* Final notes :export:

If a test with these calls gets merged, *test coverage will go up by 1 point*

This test is also created with the goal of conformance promotion.

-----
/sig testing

/sig architecture

/area conformance
