# -*- ii: apisnoop; -*-
#+TITLE:  patchCoreV1NamespacedPodStatus Test - +1
#+AUTHOR: ii team
#+TODO: TODO(t) NEXT(n) IN-PROGRESS(i) BLOCKED(b) | DONE(d)
#+OPTIONS: toc:nil tags:nil todo:nil
#+EXPORT_SELECT_TAGS: export
#+PROPERTY: header-args:sql-mode :product postgres

* TODO Progress [1/6]                                                :export:
- [X] APISnoop org-flow : [[https://github.com/apisnoop/ticket-writing/blob/master/patchCoreV1NamespacedPodStatusTest.org][patchCoreV1NamespacedPodStatusTest.org]]
- [ ] test approval issue : [[https://issues.k8s.io/][#]]
- [ ] test pr : [[https://pr.k8s.io/][!]]
- [ ] two weeks soak start date : [[https://testgrid.k8s.io/][testgrid-link]]
- [ ] two weeks soak end date : xxxx-xx-xx
- [ ] test promotion pr : [[https://pr.k8s.io/][!]]

* Identifying an untested feature Using APISnoop                     :export:

The =patchCoreV1NamespacedPodStatus= endpoint as seen on the [[https://apisnoop.cncf.io/1.24.0/stable/core/patchCoreV1NamespacedPodStatus?conformance-only=true][apisnoop.cncf.io]] website is tested but not part of conformance.
The APIsnoop query below shows that there is no conformance test for this endpoint.

  #+begin_src sql-mode :eval never-export :exports both :session none
  select distinct
    endpoint,
    test_hit AS "e2e Test",
    conf_test_hit AS "Conformance Test"
  from public.audit_event
  where endpoint ilike 'patch%PodStatus'
  and useragent like '%e2e%'
  order by endpoint
  limit 1;
  #+end_src

  #+RESULTS:
  #+begin_SRC example
              endpoint            | e2e Test | Conformance Test
  --------------------------------+----------+------------------
   patchCoreV1NamespacedPodStatus | t        | f
  (1 row)

  #+end_SRC

* API Reference and feature documentation                            :export:
- [[https://kubernetes.io/docs/reference/kubernetes-api/][Kubernetes API Reference Docs]]
- [[https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/][Kubernetes API > Workload Resources > Pod]]
- [[https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/core/v1/pod.go#L42-L58][client-go: core/v1/pod.go]]

* Test outline                                                       :export:

#+begin_src
Feature: Test patch PodStatus api endpoint
#+end_src

- patchCoreV1NamespacedPodStatus

#+begin_src
Scenario: the test patches a pod status subresource
  Given the e2e test has a running pod
  And a valid payload has been created
  When the test patches the pod status subresource
  Then the requested action is accepted without any error
  And the applied status subresource is accepted
  And the newly applied changes are found
#+end_src

* E2E Test                                                           :export:

Using a number of existing e2e test practices a new [[https://github.com/ii/kubernetes/blob/patch-pod-status-test/test/e2e/common/node/pods.go#L1074-L1115][ginkgo test]] has been created for this pod status endpoint. The e2e logs for this test are listed below.

#+begin_src
[It] should patch a pod status
  /home/ii/go/src/k8s.io/kubernetes/test/e2e/common/node/pods.go:1059
STEP: Create a pod
Jun 22 10:51:22.936: INFO: Waiting up to 5m0s for pod "pod-28pmv" in namespace "pods-5830" to be "running"
Jun 22 10:51:22.957: INFO: Pod "pod-28pmv": Phase="Pending", Reason="", readiness=false. Elapsed: 21.06407ms
Jun 22 10:51:24.964: INFO: Pod "pod-28pmv": Phase="Running", Reason="", readiness=true. Elapsed: 2.027491772s
Jun 22 10:51:24.964: INFO: Pod "pod-28pmv" satisfied condition "running"
STEP: patching /status
Jun 22 10:51:24.999: INFO: Status Message: "Patched by e2e test" and Reason: "E2E"
#+end_src

* Verifying increase in coverage with APISnoop                       :export:
** Listing endpoints hit by the updated e2e test

This query shows the pod status endpoints hit within a short period of running the e2e test.

#+begin_src sql-mode :eval never-export :exports both :session none
select distinct  endpoint, right(useragent,25) AS useragent
from testing.audit_event
where endpoint ilike '%PodStatus'
and release_date::BIGINT > round(((EXTRACT(EPOCH FROM NOW()))::numeric)*1000,0) - 60000
and useragent like 'e2e%should%'
order by endpoint
limit 5;
#+end_src

#+RESULTS:
#+begin_SRC example
            endpoint            |         useragent
--------------------------------+---------------------------
 patchCoreV1NamespacedPodStatus | should patch a pod status
(1 row)

#+end_SRC

* Final notes                                                        :export:

If a test with these calls gets merged, test coverage will go up by 1 point.

This test is also created with the goal of conformance promotion.


-----
/sig testing

/sig architecture

/area conformance
