# -*- ii: apisnoop; -*-
#+TITLE: StorageV1 CSIDriver Test
#+AUTHOR: ii team
#+TODO: TODO(t) NEXT(n) IN-PROGRESS(i) BLOCKED(b) | DONE(d)
#+OPTIONS: toc:nil tags:nil todo:nil
#+EXPORT_SELECT_TAGS: export
#+PROPERTY: header-args:sql-mode :product postgres


* TODO Progress [1/6]                                                :export:
- [ ] APISnoop org-flow : [[https://github.com/apisnoop/ticket-writing/blob/master/StorageV1CSIDriverTest.org][StorageV1CSIDriverTest.org]]
- [ ] test approval issue : [[https://issues.k8s.io/][#]]
- [ ] test pr : [[https://pr.k8s.io/][!]]
- [ ] two weeks soak start date : [[https://testgrid.k8s.io/][testgrid-link]]
- [ ] two weeks soak end date : xxxx-xx-xx
- [ ] test promotion pr : [[https://pr.k8s.io/][!]]

* Identifying an untested feature Using APISnoop                     :export:

According to following APIsnoop query, there are still 3 CSIDriver endpoints that are not tested for Conformance.

  #+NAME: untested_stable_core_endpoints
  #+begin_src sql-mode :eval never-export :exports both :session none
    SELECT
      endpoint,
      path,
      kind
      FROM testing.untested_stable_endpoint
      where eligible is true
      and endpoint ilike '%CSIDriver'
      order by kind, endpoint
      limit 10;
  #+end_src

  #+RESULTS: untested_stable_core_endpoints
  #+begin_SRC example
                endpoint              |                   path                    |   kind
  ------------------------------------+-------------------------------------------+-----------
   deleteStorageV1CollectionCSIDriver | /apis/storage.k8s.io/v1/csidrivers        | CSIDriver
   patchStorageV1CSIDriver            | /apis/storage.k8s.io/v1/csidrivers/{name} | CSIDriver
   replaceStorageV1CSIDriver          | /apis/storage.k8s.io/v1/csidrivers/{name} | CSIDriver
  (3 rows)

  #+end_SRC

- https://apisnoop.cncf.io/1.27.0/stable/storage/deleteStorageV1CollectionCSIDriver
- https://apisnoop.cncf.io/1.27.0/stable/storage/patchStorageV1CSIDriver
- https://apisnoop.cncf.io/1.27.0/stable/storage/replaceStorageV1CSIDriver

* API Reference and feature documentation                            :export:

- [[https://kubernetes.io/docs/reference/kubernetes-api/][Kubernetes API Reference Docs]]
- [[https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/csi-driver-v1/][Kubernetes API / Config and Storage Resources / CSIDriver]]
- [[https://github.com/kubernetes/client-go/tree/master/kubernetes/typed/storage/v1/csidriver.go][client-go - CSIDriver]]

* Test outline                                                       :export:

#+begin_src
Scenario: Test the lifecycle of a CSI driver

  Given the e2e test has created two csi drivers
  When the test reads each csi driver
  Then the requested action is accepted without any error
  And for each retrieved driver the UID equals the created driver's UID

  Given the e2e test has created two csi drivers
  When the test patches a csi driver with a new label
  Then the requested action is accepted without any error
  And the retrieved driver has a label with a value of "patched"

  Given the e2e test has created two csi drivers
  When the test updates a csi driver label
  Then the requested action is accepted without any error
  And the retrieved driver has a label with a value of "updated"

  Given the e2e test has created two csi drivers
  When the test lists all the csi drivers with a label
  Then the requested action is accepted without any error
  And the retrieved driverList has a length of two

  Given the e2e test has created two csi drivers
  When the test deletes a csi driver
  Then the requested action is accepted without any error
  And when that driver is subsequently read it is not found

  Given the e2e test has deleted one csi drivers
  When the test deletes the other csi driver via deleteCollection
  Then the requested action is accepted without any error
  And when that driver is subsequently read it is not found
#+end_src

* E2E Test                                                           :export:

Using a number of existing e2e test practices a new [[https://github.com/ii/kubernetes/blob/create-csidriver-test/test/e2e/storage/csi_inline.go#L233-L346][ginkgo test]] has been created to address these 3 endpoints.
The e2e logs for this test are listed below.

#+begin_src
[sig-storage] CSIInlineVolumes should run through the lifecycle of a csiDriver
/home/ii/go/src/k8s.io/kubernetes/test/e2e/storage/csi_inline.go:233
  STEP: Creating a kubernetes client @ 05/18/23 09:03:47.527
  May 18 09:03:47.527: INFO: >>> kubeConfig: /home/ii/.kube/config
  STEP: Building a namespace api object, basename csiinlinevolumes @ 05/18/23 09:03:47.528
  STEP: Waiting for a default service account to be provisioned in namespace @ 05/18/23 09:03:47.554
  STEP: Waiting for kube-root-ca.crt to be provisioned in namespace @ 05/18/23 09:03:47.555
  STEP: Creating two CSIDrivers @ 05/18/23 09:03:47.557
  STEP: Getting "inline-driver-bbba5a5b-5180-47f5-87cc-6afdfb35f77a" & "inline-driver-d834159c-f7a2-4668-9501-48eb292adb5b" @ 05/18/23 09:03:47.578
  STEP: Patching the CSIDriver "inline-driver-d834159c-f7a2-4668-9501-48eb292adb5b" @ 05/18/23 09:03:47.581
  STEP: Updating the CSIDriver "inline-driver-d834159c-f7a2-4668-9501-48eb292adb5b" @ 05/18/23 09:03:47.621
  STEP: Listing all CSIDrivers with the labelSelector: "e2e-test=csiinlinevolumes-5332" @ 05/18/23 09:03:47.654
  STEP: Deleting csiDriver "inline-driver-bbba5a5b-5180-47f5-87cc-6afdfb35f77a" @ 05/18/23 09:03:47.658
  STEP: Confirm deletion of csiDriver "inline-driver-bbba5a5b-5180-47f5-87cc-6afdfb35f77a" @ 05/18/23 09:03:47.691
  STEP: Deleting csiDriver "inline-driver-d834159c-f7a2-4668-9501-48eb292adb5b" via DeleteCollection @ 05/18/23 09:03:47.695
  STEP: Confirm deletion of csiDriver "inline-driver-d834159c-f7a2-4668-9501-48eb292adb5b" @ 05/18/23 09:03:47.706
  May 18 09:03:47.709: INFO: Waiting up to 7m0s for all (but 0) nodes to be ready
  STEP: Destroying namespace "csiinlinevolumes-5332" for this suite. @ 05/18/23 09:03:47.713
#+end_src

* Verifying increase in coverage with APISnoop                       :export:
** Listing endpoints hit by the new e2e test

This query shows the following csiDriver endpoints are hit within a short period of running this e2e test.

#+begin_src sql-mode :eval never-export :exports both :session none
select distinct substring(endpoint from '\w+') AS endpoint,
                right(useragent,47) AS useragent
from testing.audit_event
where useragent like 'e2e%should%'
  and release_date::BIGINT > round(((EXTRACT(EPOCH FROM NOW()))::numeric)*1000,0) - 20000
  and endpoint ilike '%CSIDriver%'
order by endpoint
limit 10;
#+end_src

#+RESULTS:
#+begin_SRC example
              endpoint              |                    useragent
------------------------------------+-------------------------------------------------
 createStorageV1CSIDriver           | should run through the lifecycle of a csiDriver
 deleteStorageV1CollectionCSIDriver | should run through the lifecycle of a csiDriver
 deleteStorageV1CSIDriver           | should run through the lifecycle of a csiDriver
 listStorageV1CSIDriver             | should run through the lifecycle of a csiDriver
 patchStorageV1CSIDriver            | should run through the lifecycle of a csiDriver
 readStorageV1CSIDriver             | should run through the lifecycle of a csiDriver
 replaceStorageV1CSIDriver          | should run through the lifecycle of a csiDriver
(7 rows)

#+end_SRC

* Final notes                                                        :export:

If a test with these calls gets merged, *test coverage will go up by 3 points*

This test is also created with the goal of conformance promotion.

-----
/sig testing

/sig architecture

/area conformance
